/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Pro-Visa Systems design tokens
        primary: '#001229',
        'on-primary': '#ffffff',
        'primary-container': '#0f2744',
        'on-primary-container': '#798fb1',
        'inverse-primary': '#b2c8ed',
        secondary: '#0051d5',
        'on-secondary': '#ffffff',
        'secondary-container': '#316bf3',
        'on-secondary-container': '#fefcff',
        tertiary: '#00160b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#002d1c',
        'on-tertiary-container': '#00a16f',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f9f9ff',
        'on-background': '#111c2d',
        surface: '#f9f9ff',
        'surface-dim': '#cfdaf2',
        'surface-bright': '#f9f9ff',
        'surface-variant': '#d8e3fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eeff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fb',
        'on-surface': '#111c2d',
        'on-surface-variant': '#44474d',
        'inverse-surface': '#263143',
        'inverse-on-surface': '#ecf1ff',
        outline: '#74777e',
        'outline-variant': '#c4c6ce',
        'surface-tint': '#4a5f7f',
        'primary-fixed': '#d4e3ff',
        'primary-fixed-dim': '#b2c8ed',
        'on-primary-fixed': '#021c39',
        'on-primary-fixed-variant': '#324866',
        'secondary-fixed': '#dbe1ff',
        'secondary-fixed-dim': '#b4c5ff',
        'on-secondary-fixed': '#00174b',
        'on-secondary-fixed-variant': '#003ea8',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Hanken Grotesk', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'code-data': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      spacing: {
        'sidebar-width': '260px',
        'sidebar-collapsed': '72px',
        'container-padding': '2rem',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        card: '0px 1px 3px rgba(0,0,0,0.05)',
        modal: '0px 4px 24px rgba(0,0,0,0.12)',
      },
    },
  },
  plugins: [],
}
